### ISSUE TITLE
Template error for cases where an option is false.

### ISSUE THREAD

**Issue by jdavid5815** [linuxhq/ansible-role-logrotate#1]
Hi,

When I set the option "compress" to "false", the output in both /etc/logrotate.conf and /etc/logrotate_d/<whatever> yields:

compress 0

This is incorrect syntax and logrotate will show an error if you run it manually.

The "zero" behind compress is a result of the template parsing. A {{ key }} is checked to see if it is "true" and if so {{ key }} is placed in the config file. Next, a bunch of other stuff is checked, such as whether the {{ key }} is a string or a number.. but if nothing matches, the default is:
{{ key }} {{ value}}

The case "compress: false" is not found or checked and so the default rule is applied with "false" evaluating to "0". Hence the fault.

To fix this, simply check for "false" as well:

{%     if value is sameas true %}
{{ key }}
{%     elif value is sameas false %}
#{{ key }}
{%     elif value is string %}
{{ key }} {{ value|string }}
{%     elif value is number %}
{{ key }} {{ value|int }}
{%     else %}
{{ key }} {{ value }}
{%     endif %}

**Comment by tkimball83** [comment]
Role has been updated and tagged with version v0.0.8.

Please confirm all looks well from your end, thanks!

**Comment by jdavid5815** [comment]
Yep, work fine now. Thanks. On a side note, the documentation should really mention that you can also use postrotate with a list of scripts, etc.. and that the "endscript" tag will be placed automatically.

For example:
options:
  minsize: 1M
  monthly: true
  rotate: 1
  postrotate:
    - "/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true"

**Comment by tkimball83** [comment]
@jdavid5815 - Please send in a PR with the updated documentation from an end users perspective and I'll merge it.

I'm going to mark this case as solved as the template issue has been fixed.

Thanks!
